version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
#    volumes:
#      - "./dependencies/jaeger/jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
#    command: --query.ui-config /etc/jaeger/jaeger-ui.json
#    environment:
#      - METRICS_STORAGE_TYPE=prometheus
#      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "16686:16686" # UI
#    networks:
#      - static-network
